hybrid_a_star:
  search_phase:
    default_sim_time: 60
    precision_phase_distance: 1000
    precision_phase_sim_time: 20
  search_pruning:
    prune_radius_explored: 25
    prune_radius_closed: 25
  heuristic:
    voronoi_field_cost_weight: 0.005

mission_planner:
  #Name of mission, for path and debug data storage
  mission_name: "testmission"
  #If path determined in advance and stored to gpx, load it and publish
  load_from_gpx: false
  #Load from this gpx or save to this gpx
  gpx_name: "debug"
  #Preprocessing has been run for mission region
  preprocessed_map: false
  #Preprocessed data to load (or save). Loads/saves collision db, voronoi db and quadtree 
  map_name: "test_mission_region_2"
  # Two coordinates defining the mission region. Discarded if preprocessed_map=true (min_lon,min_lat,max_lon,max_lat)
  map_extent: [-74.02483,40.49961,-73.72579,40.64967]
  #Desired speed of the vessel planning for
  desired_speed: 5


  
