a_star:
  mission_data:
    save_search_data: true
hybrid_a_star:
  static_simulation_time:
    default_sim_time: 120 #s
  adaptive_simulation_time:
    #Should adaptive simulation time be used (alternative is fixed)
    enable_adaptive_sim_time: true
    #The lower limit for sim time when land distance smallest
    underway_sim_time_minimum: 30 #s
    #The scaling factor for sim time when approaching goal
    approach_sim_time_scaling: 0.03
    #Lower limit sim time when approaching goal
    approach_sim_time_minimum: 15 #s
  search_pruning:
    prune_radius_explored: 20
    prune_radius_closed: 20
  heuristic:
    distance_scaling_factor: 1.25
    voronoi_field_cost_weight: 0.005
  mission_data:
    save_search_data: true
    save_benchmark_data: true


  
