hybrid_a_star:
  search_phase:
    default_sim_time: 240
    approach_phase_distance: 10000
    precision_phase_distance: 2500
    approach_phase_sim_time: 60
    precision_phase_sim_time: 25
  search_pruning:
    prune_radius_explored: 50
    prune_radius_closed: 50
  heuristic:
    distance_scaling_factor: 1.05
    voronoi_field_cost_weight: 0.005

mission_planner:
  #Name of mission, for path and debug data storage
  mission_name: "test_matchsequence_trondheim_4x_105"
  #If path determined in advance and stored to gpx, load it and publish
  load_from_gpx: false
  #Load from this gpx or save to this gpx
  gpx_name: "debug"
  #Preprocessing has been run for mission region
  preprocessed_map: true
  #Preprocessed data to load (or save). Loads/saves collision db, voronoi db and quadtree 
  map_name: "trondheim_hitra_4x"
  # Two coordinates defining the mission region. Discarded if preprocessed_map=true (min_lon,min_lat,max_lon,max_lat)
  map_extent: [9.26396,63.40249,10.49051,63.73362]
  #Desired speed of the vessel planning for
  desired_speed: 5


  
