monte_carlo_supervisor:
  leader: true
  simulation_collection_name: "headon_colav_debug_bugfix_"
  simulations: 2
  predefined_mission: true
  predefined_mission_name: "usv_headon"
  goal_pose: [-74.01067,40.58611,0]